services:
  postgres:
    image: postgres:13
    container_name: chat-postgres
    environment:
      POSTGRES_USER: chat-root
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
